spring.application.name=campus-navigation-backend

# PostgreSql
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/hanyang_map}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}

# 요청 좌표계 srid
navigation.request-srid=4326

# 내부 계산용 좌표계
navigation.metric-srid=5186

# 현재 위치 기준 시작 후보 노드를 찾을 반경
navigation.candidate-radius-meters=10.0

# 시작 후보 노드의 최대 개수
navigation.max-start-candidates=20


navigation.projection-radius-meters=10.0
navigation.projection-max-candidates=20
navigation.spatial-index-cell-size-meters=25.0


# 보행 가능한 도로 유형 목록
navigation.walkable-highways[0]=footway
navigation.walkable-highways[1]=pedestrian
navigation.walkable-highways[2]=steps
navigation.walkable-highways[3]=path
navigation.walkable-highways[4]=corridor
navigation.walkable-highways[5]=living_street
