spring.application.name=campus-navigation-backend

# PostgreSql
spring.datasource.url=jdbc:postgresql://localhost:5432/hanyang_map
spring.datasource.username=postgres
spring.datasource.password=park74765@

# ?? ?? ??? srid
navigation.request-srid=4326

# ?? ??? ???
navigation.metric-srid=5186

# ?? ?? ?? ?? ?? ?? ?? ??
navigation.candidate-radius-meters=10.0

# ?? ?? ??? ?? ? ?? ? ??? ????
navigation.max-start-candidates=20

# ?? ?? ??? ?? ??? ???? ???? ?? ??
navigation.walkable-highways[0]=footway
navigation.walkable-highways[1]=pedestrian
navigation.walkable-highways[2]=steps
navigation.walkable-highways[3]=path
navigation.walkable-highways[4]=corridor
navigation.walkable-highways[5]=living_street
